### ISSUE TITLE
Responsive layout

### ISSUE THREAD

**Issue by JosefJezek** [ginkgobioworks/plotly-plot#9]
Could you make this plot with responsive layout?

- https://plot.ly/javascript/responsive-fluid-layout/
- https://github.com/PolymerElements/iron-resizable-behavior

**Comment by myw** [comment]
Thank you for this idea; it seems like a very easy thing to implement, given the links you've sent. It should be as simple as adding the `IronResizable` behavior, and then calling `Plotly.Plots.resize(this.$.plot)` upon the resulting plot image when the `iron-resize` event is triggered.

I can code this up quickly, but I don't have use cases for testing; would you be able to make some demo/test code for it? Ideally, if you could write a test that currently fails, but would pass if the layout was responsive, that'd be _amazing_. If not, just testing the branch I make would be helpful.

**Comment by myw** [comment]
@JosefJezek I've implemented a solution in #10. Could you please try that out and see if it works for you?

**Comment by myw** [comment]
@JosefJezek plotly-plot 0.4.0 should do what you need

**Comment by JosefJezek** [comment]
Thank you
